# Generated by Django 4.2.7 on 2023-12-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('all', 'All Animals'), ('dogs', 'Dogs'), ('cats', 'Cats')], max_length=50)),
                ('image_url', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
    ]
