# Generated by Django 4.2.7 on 2023-12-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_animal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='category',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='image_url',
        ),
        migrations.AddField(
            model_name='animal',
            name='digital',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='animal',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=228, null=True),
        ),
    ]
