# Generated by Django 4.2.7 on 2023-12-19 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='about_us_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='about_us_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='animals',
        ),
        migrations.AddField(
            model_name='order',
            name='animals',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.animal'),
        ),
    ]
