# Generated by Django 4.2.7 on 2023-12-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_aboutus_remove_order_animals_order_animals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='animals',
        ),
        migrations.AddField(
            model_name='order',
            name='animals',
            field=models.ManyToManyField(to='main.animal'),
        ),
    ]
